name: Python pipeline

on: [push]

jobs:
  test:
    runs-on : ubuntu-latest
    steps :
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Python
      run: python hello.py
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps :
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello
        path: .
      
